### ISSUE TITLE
Fix crash

### ISSUE THREAD

**Issue by sagudev** [sagudev/spidershim#1]
```
running hello-world
./hello-world
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from SpiderShim
[ RUN      ] SpiderShim.HelloWorld
[       OK ] SpiderShim.HelloWorld (491 ms)
[----------] 1 test from SpiderShim (491 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (491 ms total)
[  PASSED  ] 1 test.
make[1]: Leaving directory '/home/samo/Namizje/spidershim/target/test'
samo@medion:~/Namizje/spidershim$ gdb ./target/test/hello-world 
GNU gdb (Ubuntu 10.1-2ubuntu2) 10.1.90.20210411-git
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./target/test/hello-world...
(gdb) r
Starting program: /home/samo/Namizje/spidershim/target/test/hello-world 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from SpiderShim
[ RUN      ] SpiderShim.HelloWorld
[New Thread 0x7ffff79ee640 (LWP 13467)]
[Thread 0x7ffff79ee640 (LWP 13467) exited]
[New Thread 0x7ffff71ed640 (LWP 13468)]
[New Thread 0x7ffff6fee640 (LWP 13469)]
[New Thread 0x7ffff6def640 (LWP 13470)]
[New Thread 0x7ffff6bf0640 (LWP 13471)]
[New Thread 0x7ffff69f1640 (LWP 13472)]
[New Thread 0x7ffff67f2640 (LWP 13473)]
[New Thread 0x7ffff65f3640 (LWP 13474)]
[New Thread 0x7ffff63f4640 (LWP 13475)]
Hit MOZ_CRASH(Association for 0x38d582f99100 ObjectSlots has different size: expected 0x100 but got 0x800) at /home/samo/Namizje/spidershim/mozjs/js/src/gc/Scheduling.cpp:593

Thread 1 "hello-world" received signal SIGSEGV, Segmentation fault.
0x0000000001beeeb4 in MOZ_Crash (aFilename=0x2838f3 "/home/samo/Namizje/spidershim/mozjs/js/src/gc/Scheduling.cpp", aLine=593, 
    aReason=0x3254870 <sPrintfCrashReason> "Association for 0x38d582f99100 ObjectSlots has different size: expected 0x100 but got 0x800") at /home/samo/Namizje/spidershim/target/mozjs/dist/include/mozilla/Assertions.h:332
332	  MOZ_REALLY_CRASH(aLine);
(gdb) bt
#0  0x0000000001beeeb4 in MOZ_Crash (aFilename=0x2838f3 "/home/samo/Namizje/spidershim/mozjs/js/src/gc/Scheduling.cpp", aLine=593, 
    aReason=0x3254870 <sPrintfCrashReason> "Association for 0x38d582f99100 ObjectSlots has different size: expected 0x100 but got 0x800") at /home/samo/Namizje/spidershim/target/mozjs/dist/include/mozilla/Assertions.h:332
#1  js::gc::MemoryTracker::untrackGCMemory (this=0x345f2f0, cell=0x38d582f99100, nbytes=2048, use=js::MemoryUse::ObjectSlots)
    at /home/samo/Namizje/spidershim/mozjs/js/src/gc/Scheduling.cpp:590
#2  0x0000000001853c81 in js::ZoneAllocator::removeCellMemory (this=0x345f220, cell=0x38d582f99100, nbytes=2048, 
    use=js::MemoryUse::ObjectSlots, wasSwept=true) at /home/samo/Namizje/spidershim/mozjs/js/src/gc/ZoneAllocator.h:98
#3  0x0000000001853a4a in js::RemoveCellMemory (cell=0x38d582f99100, nbytes=2048, use=js::MemoryUse::ObjectSlots, wasSwept=true)
    at /home/samo/Namizje/spidershim/mozjs/js/src/gc/ZoneAllocator.h:321
#4  0x00000000018539b5 in js::RemoveCellMemory (cell=0x38d582f99100, nbytes=2048, use=js::MemoryUse::ObjectSlots, wasSwept=true)
    at /home/samo/Namizje/spidershim/mozjs/js/src/gc/ZoneAllocator.h:327
#5  0x00000000018021c1 in JSFreeOp::removeCellMemory (this=0x7fffffffd628, cell=0x38d582f99100, nbytes=2048, 
    use=js::MemoryUse::ObjectSlots) at /home/samo/Namizje/spidershim/mozjs/js/src/gc/FreeOp-inl.h:53
#6  0x0000000001936a86 in JSFreeOp::free_ (this=0x7fffffffd628, cell=0x38d582f99100, p=0x32c30c0, nbytes=2048, 
    use=js::MemoryUse::ObjectSlots) at /home/samo/Namizje/spidershim/mozjs/js/src/gc/FreeOp-inl.h:17
#7  0x0000000001a2098d in JSObject::finalize (this=0x38d582f99100, fop=0x7fffffffd628)
    at /home/samo/Namizje/spidershim/mozjs/js/src/vm/JSObject-inl.h:96
#8  0x0000000001a203bb in js::gc::Arena::finalize<JSObject> (this=0x38d582f99000, fop=0x7fffffffd628, 
    thingKind=js::gc::AllocKind::OBJECT16, thingSize=160) at /home/samo/Namizje/spidershim/mozjs/js/src/gc/GC.cpp:486
#9  0x0000000001a1d94f in FinalizeTypedArenas<JSObject> (fop=0x7fffffffd628, src=0x345f858, dest=..., 
    thingKind=js::gc::AllocKind::OBJECT16, budget=...) at /home/samo/Namizje/spidershim/mozjs/js/src/gc/GC.cpp:541
#10 0x00000000019de73e in FinalizeArenas (fop=0x7fffffffd628, src=0x345f858, dest=..., thingKind=js::gc::AllocKind::OBJECT16, 
    budget=...) at /home/samo/Namizje/spidershim/mozjs/js/src/gc/GC.cpp:569
#11 0x00000000019f4d62 in js::gc::ArenaLists::foregroundFinalize (this=0x345f420, fop=0x7fffffffd628, 
    thingKind=js::gc::AllocKind::OBJECT16, sliceBudget=..., sweepList=...) at /home/samo/Namizje/spidershim/mozjs/js/src/gc/GC.cpp:5518
#12 0x00000000019f6a26 in js::gc::GCRuntime::finalizeAllocKind (this=0x3276d48, fop=0x7fffffffd628, budget=...)
    at /home/samo/Namizje/spidershim/mozjs/js/src/gc/GC.cpp:5790
#13 0x0000000001a3a1fa in sweepaction::SweepActionCall::run (this=0x3286650, args=...)
    at /home/samo/Namizje/spidershim/mozjs/js/src/gc/GC.cpp:5911
#14 0x0000000001a3befe in sweepaction::SweepActionForEach<ContainerIter<mozilla::EnumSet<js::gc::AllocKind, unsigned long> >, mozilla::EnumSet<js::gc::AllocKind, unsigned long> >::run (this=0x3286670, args=...) at /home/samo/Namizje/spidershim/mozjs/js/src/gc/GC.cpp:6016
#15 0x0000000001a6a53d in sweepaction::SweepActionSequence::run (this=0x32867d0, args=...)
--Type <RET> for more, q to quit, c to continue without paging--c
    at /home/samo/Namizje/spidershim/mozjs/js/src/gc/GC.cpp:5981
#16 0x0000000001a3b050 in sweepaction::SweepActionForEach<js::gc::SweepGroupZonesIter, JSRuntime*>::run (this=0x32868b0, args=...) at /home/samo/Namizje/spidershim/mozjs/js/src/gc/GC.cpp:6016
#17 0x0000000001a6a53d in sweepaction::SweepActionSequence::run (this=0x32868f0, args=...) at /home/samo/Namizje/spidershim/mozjs/js/src/gc/GC.cpp:5981
#18 0x0000000001a39360 in sweepaction::SweepActionForEach<js::gc::SweepGroupsIter, JSRuntime*>::run (this=0x3286a60, args=...) at /home/samo/Namizje/spidershim/mozjs/js/src/gc/GC.cpp:6016
#19 0x00000000019f82af in js::gc::GCRuntime::performSweepActions (this=0x3276d48, budget=...) at /home/samo/Namizje/spidershim/mozjs/js/src/gc/GC.cpp:6159
#20 0x00000000019fb6ec in js::gc::GCRuntime::incrementalSlice (this=0x3276d48, budget=..., gckind=..., reason=JS::GCReason::DESTROY_RUNTIME, session=...) at /home/samo/Namizje/spidershim/mozjs/js/src/gc/GC.cpp:6694
#21 0x00000000019fdaed in js::gc::GCRuntime::gcCycle (this=0x3276d48, nonincrementalByAPI=true, budget=..., gckind=..., reason=JS::GCReason::DESTROY_RUNTIME) at /home/samo/Namizje/spidershim/mozjs/js/src/gc/GC.cpp:7104
#22 0x00000000019ff11b in js::gc::GCRuntime::collect (this=0x3276d48, nonincrementalByAPI=true, budget=..., gckindArg=..., reason=JS::GCReason::DESTROY_RUNTIME) at /home/samo/Namizje/spidershim/mozjs/js/src/gc/GC.cpp:7315
#23 0x00000000019beebb in js::gc::GCRuntime::gc (this=0x3276d48, gckind=GC_NORMAL, reason=JS::GCReason::DESTROY_RUNTIME) at /home/samo/Namizje/spidershim/mozjs/js/src/gc/GC.cpp:7391
#24 0x0000000001d0f209 in JSRuntime::destroyRuntime (this=0x3276620) at /home/samo/Namizje/spidershim/mozjs/js/src/vm/Runtime.cpp:287
#25 0x0000000001947917 in js::DestroyContext (cx=0x3283e00) at /home/samo/Namizje/spidershim/mozjs/js/src/vm/JSContext.cpp:223
#26 0x00000000017fb2c5 in JS_DestroyContext (cx=0x3283e00) at /home/samo/Namizje/spidershim/mozjs/js/src/jsapi.cpp:396
#27 0x000000000317c85e in v8::Isolate::~Isolate() ()
#28 0x000000000317cce8 in v8::Isolate::Dispose() ()
#29 0x00000000017f5494 in SpiderShim_HelloWorld_Test::TestBody() ()
#30 0x00000000031be4d4 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#31 0x00000000031af9dd in testing::Test::Run() ()
#32 0x00000000031b05e0 in testing::TestInfo::Run() ()
#33 0x00000000031b0d97 in testing::TestCase::Run() ()
#34 0x00000000031b9587 in testing::internal::UnitTestImpl::RunAllTests() ()
#35 0x00000000031bf014 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ()
#36 0x00000000031b90ea in testing::UnitTest::Run() ()
#37 0x00000000031d2d6c in main ()

```

**Comment by sagudev** [comment]
Probably should do proper fix of https://github.com/sagudev/spidershim/commit/42678668c36a211cba0206fcf33133cee0b12780
